[build]
  cmd = "go build -ldflags='-X main.mode=development' -o ./tmp/main ."
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  delay = 1
  include_ext = ["go", "css", "html", "js", "json", "yml", "yaml", "toml"]

[screen]
  clear_on_rebuild = true
  keep_scroll = true
